name: Cypress Tests

on: 
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cypress run
        run: npm run cy:open